### PR TITLE
django.conf.urls.patterns() is deprecated

### PR DESCRIPTION
**Pull request by wilima**
I hope that this fix is ok.

### CODE REVIEW

**Comment by fission6** [comment]
thanks for this pull request, can we get this merged?

**Comment by urbaniak** [comment]
I'm also looking forward to get that change releases on pypi.

**Comment by gastlich** [comment]
@douglasmiranda please merge at least this PR, the plugin is going to be not compatible with django 1.10 :(

**Comment by madisvain** [comment]
would be very nice to get the warning to stop - so also voting for a merge on this

**Comment by douglasmiranda** [comment]
#122

**Pull request closed without merging**
