### PR TITLE
Allow using custom auth decorator for RedactorUploadView

### PR DESCRIPTION
**Pull request by fpytloun**

### CODE REVIEW

**Comment by douglasmiranda** [comment]
Thanks :D

**Comment by fpytloun** [comment]
Me too. Will you upload new version to Pypi? :-)

**Comment by douglasmiranda** [comment]
Yes I'll =] I'll try to upload today.

**Comment by douglasmiranda** [comment]
https://pypi.python.org/pypi/django-wysiwyg-redactor/

**Comment by fpytloun** [comment]
Lovely, thank you! :-)

**Pull request merged**
